source "https://rubygems.org"

gem "sinatra"
gem 'sqlite3', '~> 1.3.6'
gem "activerecord"
gem "sinatra-activerecord"
gem "sinatra-contrib"
gem 'ripl', :git => 'git@github.com:cldwalker/ripl.git', :branch => 'master'
group :development do
  gem "tux"
end
